title: Hambledon Village Shop
description: Community-owned shop, caf√©/deli and Post Office in Hambledon, Surrey.
baseurl: ""
url: "https://www.hambledonvillageshop.co.uk"
markdown: kramdown
permalink: pretty
